### PR TITLE
Fix invite censor bypass by using percent-encoding to hide from the regex

### PR DESCRIPTION
**Pull request by sudofox**
```py
>>> print unquote('https://discord.gg/%72%6f%77%62%6f%61%74')
https://discord.gg/rowboat
>>> 
```

you can bypass the invite censor by urlencoding the part of the URL that goes after. Pass it through unquote once and you can get around that.

I also fixed what looks like a typo elsewhere.

### CODE REVIEW

**Comment by sudofox** [comment]
also I think that method might be usable elsewhere besides invite links so you might want to give that a look too :'D

you can urlencode anything with this:

```
$ echo -n rowboat|xxd -p|tr -d \\n|sed 's/../%&/g'
%72%6f%77%62%6f%61%74
```

**Comment by sudofox** [comment]
Any status on this?

**Comment by sudofox** [comment]
Peace be with you!

Would be great to see some attention on this so that any and all abuse of this workaround can be curbed

**Comment by binuwu** [comment]
plsmerge

**Pull request closed without merging**
