### PR TITLE
[frontend] give the information tab some use

### PR DESCRIPTION
**Pull request by swvn9**
Right now the tab is non-functioning and confusing to users accessing it for the first time, so I've put some basic information about the guild as a placeholder until something new can be done with the page.

### CODE REVIEW

**Comment by liambagge** [comment]
can you send a screenshot of how it looks 👀

**Comment by swvn9** [comment]
Dashboard preview
I've done quite a few changes to this dashboard on the instance I host for my guilds,
but here is the info tab.

**Comment by liambagge** [comment]
cool
+1 for merging

**Comment by nullpixel** [comment]
It’s a neat PR, but the frontend is currently being rewritten in preact, and I believe that all frontend changes should be based into that branch.

The UI of the dashboard rewrite is still to be designed, too.

**Comment by b1naryth1ef** [comment]
I'm being slow on rewrite so I'll merge this.

**Pull request merged**
