### PR TITLE
Use the dashboard url from Config

### PR DESCRIPTION
**Pull request by TobiTenno**
Would you prefer I moved it into constants and load everything in there? That would reduce the config loads and everything could be read from a single location and the config would only be opened once.

### CODE REVIEW

**Comment by MrLotU** [comment]
Honestly, I think you'd have more chance of getting this merged if it wasn't a config change. Maybe include it in constatns.py instead of in the config file.

**Comment by aliasfalse** [comment]
It's already in the config file....

**Comment by aliasfalse** [comment]
And I asked a question about moving all of it to the constants file for all config params, but wasn't given a response. And after an earlier much larger change that included this in the constants, I was asked to do a PR just for this.

**Comment by MrLotU** [comment]
Okay, was just sharing my thoughts

**Comment by aliasfalse** [comment]
Nah, I totally agree that it'd be better in there, I just wanted word from b1naryth1ef before I did it so he wouldn't reject it for having too much

**Pull request closed without merging**
